version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
